### ISSUE TITLE
Does Sidecar support having another widget at the bottom?

### ISSUE THREAD

**Issue by GiacomoLaw** [gitterHQ/sidecar#53]
I would like to add the sidecar for my Gitter community. However, I also have a Talk.to widget down there. Does sidecar work fine with this?

Thanks

**Comment by MadLittleMods** [comment]
Yes, just move over the button with some CSS

```css
.gitter-open-chat-button {
  right: 250px;
}
```
