### ISSUE TITLE
How can I hide the Gitter sidebar on mobile phones? 

### ISSUE THREAD

**Issue by Vincentqyw** [gitterHQ/sidecar#65]
How can I hide the Gitter sidebar on mobile phones?

**Comment by mydigitalself** [comment]
You can probably customize the CSS with some responsive media queries to not display the button.

`options.useStyles` to false from the docs: https://sidecar.gitter.im/

**Comment by MadLittleMods** [comment]
No need to use `options.useStyles` if you just want to add some additional styles to hide the "Open chat" button and popout sidebar.

You can target `.gitter-open-chat-button`, `.gitter-chat-embed` with CSS.

```css
@media (max-width: 600px) {
    .gitter-open-chat-button,
    .gitter-chat-embed {
        display: none;
    }
}
```
